MWF.xApplication.SysSetting.LP = {
	"title": "系统设置",

	"navEmail": "系统邮箱",
	"navLogin": "登录与安全",
	"navSms": "验证码服务",
	"navAbout": "运行环境",

	"emailTitle": "系统邮箱配置",
	"emailDesc": "用于系统通知、验证码下发、密码找回等邮件。配置保存后即时生效，无需重启 O2OA。",
	"enableMail": "启用邮件通道",
	"enableMailHint": "关闭后所有系统邮件停止发送（验证码将无法投递）",
	"smtpHost": "SMTP 服务器",
	"smtpHostPh": "如 smtp.ym.163.com",
	"smtpPort": "端口",
	"ssl": "使用 SSL 加密",
	"sslHint": "465 端口通常需要开启",
	"senderMail": "发件人邮箱",
	"senderMailPh": "如 o2oa@ccia.xin",
	"senderName": "发件人名称",
	"senderNamePh": "如 o2oa_admin",
	"smtpUser": "认证账号",
	"smtpUserHint": "一般与发件人邮箱一致",
	"smtpPassword": "密码 / 授权码",
	"smtpPasswordPh": "请输入 SMTP 授权码",
	"smtpPasswordKeep": "留空表示不修改已保存的密码",
	"redirectTo": "邮件重定向到",
	"redirectToHint": "联调用：填写后所有邮件都改发到此地址（留空为正常投递）",

	"save": "保存配置",
	"reset": "重置",
	"testMail": "发送测试邮件",
	"testTo": "测试收件地址",
	"testToPh": "留空则发给当前登录用户",
	"saved": "配置已保存",
	"saveFailed": "保存失败",
	"testing": "正在发送…",
	"testOk": "测试邮件已发送，请查收",
	"testFail": "测试邮件发送失败",

	"tplPanel": "邮件模板",
	"tplHint": "支持占位符：{code} 验证码、{name} 姓名、{mobile} 手机号、{ttl} 有效期(分钟)、{app} 系统名",
	"tplCode": "验证码邮件",
	"tplReset": "密码重置邮件",
	"tplInvite": "邀请/开通邮件",
	"tplSubject": "邮件主题",
	"tplBody": "邮件正文",
	"tplRestore": "恢复默认",

	"loginTitle": "登录与安全",
	"loginDesc": "控制登录环节的验证方式。图形验证码由 O2OA 本地生成，无需联网。",
	"captchaLogin": "启用图形验证码",
	"captchaLoginHint": "登录页显示图形验证码（本地生成，离线可用）",
	"codeLogin": "启用登录短信验证码",
	"codeLoginHint": "登录时向用户绑定手机号下发验证码",
	"codeLoginChannel": "验证码通道",
	"channelLocal": "本地邮件（x_sms_assemble_control 平替）",
	"channelCloud": "O2OA 云短信（已断云，不可用）",

	"smsTitle": "验证码服务",
	"smsDesc": "自研的本地短信验证码服务（x_sms_assemble_control 平替）。验证码在本机生成，经系统邮箱投递，不依赖 O2OA 云。",
	"svcStatus": "服务状态",
	"svcRunning": "运行中",
	"svcDown": "未运行",
	"svcRegistered": "已注册到 O2OA",
	"svcUnregistered": "未注册（验证码无法下发）",
	"svcNode": "访问地址",
	"svcPort": "监听端口",
	"svcHome": "服务目录",
	"svcStartHint": "若服务未运行，请双击启动：",
	"pendingTitle": "待投递验证码",
	"pendingEmpty": "当前没有待验证的验证码",
	"pendingMobile": "手机号",
	"pendingExpire": "剩余有效",
	"sendTestCode": "测试发码",
	"sendTestCodePh": "输入手机号，如 13700000005",
	"sendTestCodeOk": "验证码已生成并投递",
	"sec": "秒",

	"aboutTitle": "运行环境",
	"aboutDesc": "本系统运行状态概览。",
	"localOnly": "离线运行（已断开 O2OA 云）",

	"back": "返回",
	"refresh": "刷新",
	"ok": "确定",
	"cancel": "取消",
	"close": "关闭",
	"loading": "加载中…",
	"loadFailed": "加载失败",
	"noPerm": "仅系统管理员（Manager）可修改此页面配置。",
	"unsaved": "有未保存的修改，确定离开吗？"
};
